catalogMode: prefer

minimumReleaseAgeExclude:
  - '@iso4/*'

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - cached-factory@0.1.0
  - ts-api-utils@2.2.0
  - undici-types@6.21.0

packages:
  - 'packages/*'

catalog:
  '@changesets/cli': ^3.0.2
  '@iso4/fetch': ^0.0.2
  '@iso4/sandbox': ^0.6.0
  '@schplitt/eslint-config': ^1.5.4
  '@types/node': ^26.5.1
  eslint: ^10.10.0
  tsdown: ^0.23.0
  tsnapi: ^1.4.2
  typescript: ^6.0.3
  vitest: ^5.0.0

onlyBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: true
