/**
 * Generated by tsnapi — public API snapshot of `durable-isolates`
 */
// #region Interfaces
export interface CompletedBoundary extends BoundaryRecordBase {
  status: "completed";
  value: unknown;
}
export interface CompletedResult extends ExecuteResultBase {
  outcome: "completed";
  result: unknown;
}
export interface DurableIsolates {
  hydrate: (_: HydrateOptions) => Promise<DurableIsolatesRunner>;
  dispose: () => Promise<void>;
}
export interface DurableIsolatesOptions {
  sandbox?: SandboxOptions;
}
export interface DurableIsolatesRunner {
  execute: (_: ExecuteOptions) => ExecuteHandle;
  dispose: () => Promise<void>;
}
export interface ExecuteHandle {
  result: Promise<ExecuteResult>;
  suspend: () => Promise<ExecuteResult>;
}
export interface ExecuteOptions {
  code: string;
  cache: BoundaryCache;
  globals?: PerExecuteGlobals;
  limits?: Partial<ResourceLimits>;
}
export interface FailedBoundary extends BoundaryRecordBase {
  status: "failed";
  error: unknown;
}
export interface FailedResult extends ExecuteResultBase {
  outcome: "failed";
  error: unknown;
}
export interface HydrateOptions {
  modules: Readonly<Record<string, ModuleDefinition>>;
  limits?: Partial<ResourceLimits>;
}
export interface ModuleDefinition {
  shim: string;
  globals?: GlobalMap;
}
export interface PendingOperation {
  id: string;
  name: string;
  payload: unknown;
}
export interface SuspendedResult extends ExecuteResultBase {
  outcome: "suspended";
  pending: PendingOperation[];
}
export interface WaitingBoundary extends BoundaryRecordBase {
  status: "waiting";
  name: string;
}
// #endregion

// #region Types
export type BoundaryCache = Record<string, BoundaryRecord>;
export type BoundaryRecord = CompletedBoundary | FailedBoundary | WaitingBoundary;
export type CreateDurableIsolates = (_?: DurableIsolatesOptions) => DurableIsolates;
export type ExecuteResult = CompletedResult | SuspendedResult | FailedResult;
export type GlobalMap = Readonly<Record<string, HostGlobal>>;
export type HostGlobal = (..._: unknown[]) => unknown;
export type PerExecuteGlobals = Readonly<Record<string, HostGlobal>>;
// #endregion

// #region Classes
export declare class SuspendIsolate extends Error {
  readonly payload: unknown;
  constructor(_?: unknown);
}
// #endregion

// #region Variables
export declare const durableIsolates: CreateDurableIsolates;
// #endregion