/**
 * Generated by tsnapi — public API snapshot of `durable-isolates`
 */
// #region Interfaces
export interface CompletedBoundary extends BoundaryRecordBase {
  status: "completed";
  name?: string;
  args?: unknown[];
  value: unknown;
}
export interface CompletedResult extends ExecuteResultBase {
  outcome: "completed";
  result: unknown;
  run: RunSuccess;
}
export interface DivergenceRejection extends RejectionBase {
  reason: "divergence";
  mismatch: "name" | "args" | "no-call";
  recorded: {
    name?: string;
    args?: unknown[];
  };
  attempted: {
    name: string;
    args: unknown[];
  };
}
export interface DurableIsolates {
  prepare: (_: PrepareOptions) => Promise<DurableIsolatesRunner>;
  getSandbox: () => Promise<Sandbox>;
  dispose: () => Promise<void>;
}
export interface DurableIsolatesOptions {
  sandbox?: SandboxOptions;
}
export interface DurableIsolatesRunner {
  readonly prefixId: string;
  execute: (_: ExecuteOptions) => ExecuteHandle;
  dispose: () => Promise<void>;
}
export interface ExecuteHandle {
  result: Promise<ExecuteResult>;
  suspend: () => Promise<ExecuteResult>;
}
export interface ExecuteOptions {
  code: string;
  cache: BoundaryCache;
  globals?: PerExecuteGlobals;
  limits?: Partial<ResourceLimits>;
}
export interface FailedBoundary extends BoundaryRecordBase {
  status: "failed";
  name?: string;
  args?: unknown[];
  error: unknown;
}
export interface FailedResult extends ExecuteResultBase {
  outcome: "failed";
  error: RunError;
  run: RunFailure;
}
export interface ModuleDefinition {
  shim: string;
  globals?: GlobalMap;
}
export interface NonJsonCallRejection extends NonJsonRejectionBase {
  source: "args" | "result" | "error";
  name: string;
}
export interface NonJsonCommitRejection extends NonJsonRejectionBase {
  source: "commit";
}
export interface PendingOperation {
  id: string;
  name: string;
  payload: unknown;
}
export interface PrepareOptions {
  modules: Readonly<Record<string, ModuleDefinition>>;
  limits?: Partial<ResourceLimits>;
}
export interface RejectedResult extends ExecuteResultBase {
  outcome: "rejected";
  rejection: Rejection;
  run: RunResult;
}
export interface SuspendedResult extends ExecuteResultBase {
  outcome: "suspended";
  pending: PendingOperation[];
  run: RunResult;
}
export interface WaitingBoundary extends BoundaryRecordBase {
  status: "waiting";
  name: string;
  args: unknown[];
}
// #endregion

// #region Types
export type BoundaryCache = Record<string, BoundaryRecord>;
export type BoundaryRecord = CompletedBoundary | FailedBoundary | WaitingBoundary;
export type CreateDurableIsolates = (_?: DurableIsolatesOptions) => DurableIsolates;
export type ExecuteResult = CompletedResult | SuspendedResult | FailedResult | RejectedResult;
export type GlobalMap = Readonly<Record<string, HostGlobal>>;
export type HostGlobal = (..._: unknown[]) => unknown;
export type NonJsonRejection = NonJsonCallRejection | NonJsonCommitRejection;
export type PerExecuteGlobals = Readonly<Record<string, HostGlobal>>;
export type Rejection = NonJsonRejection | DivergenceRejection;
// #endregion

// #region Classes
export declare class SuspendIsolate extends Error {
  readonly payload: unknown;
  constructor(_?: unknown);
}
// #endregion

// #region Variables
export declare const durableIsolates: CreateDurableIsolates;
export declare const KERNEL_BRIDGE_GLOBALS: readonly [typeof DURABLE_CALL_GLOBAL, typeof DURABLE_LOOKUP_GLOBAL, typeof DURABLE_COMMIT_GLOBAL];
// #endregion

// #region Referenced (internal)
interface BoundaryRecordBase {
  seq: number;
}
interface ExecuteResultBase {
  cache: BoundaryCache;
  run: RunResult;
}
interface NonJsonRejectionBase extends RejectionBase {
  reason: "non-json";
  detail: string;
}
interface RejectionBase {
  key: string;
  message: string;
}
// #endregion