/**
 * Generated by tsnapi — public API snapshot of `durable-isolates`
 */
// #region Interfaces
export interface CompletedBoundary extends BoundaryRecordBase {
  status: "completed";
  name?: string;
  args?: unknown[];
  value: unknown;
}
export interface CompletedResult extends ExecuteResultBase {
  outcome: "completed";
  result: unknown;
  run: RunSuccess;
}
export interface DivergenceRejection extends RejectionBase {
  reason: "divergence";
  mismatch: "order" | "name" | "args" | "kind";
  recorded: {
    key: string;
    name?: string;
    args?: unknown[];
    scope?: string;
    order?: number;
  };
  attempted: {
    scope: string;
    order: number;
    name: string;
    args: unknown[];
  } | {
    scope: string;
    order: number;
  };
}
export interface DuplicateKeyRejection extends RejectionBase {
  reason: "duplicate-key";
  detail: "used twice in this run" | "already recorded";
}
export interface DurableIsolates {
  prepare: (_: PrepareOptions) => Promise<DurableIsolatesRunner>;
  getSandbox: () => Promise<Sandbox>;
  run: (_: RunOptions) => ExecuteHandle;
  dispose: () => Promise<void>;
}
export interface DurableIsolatesOptions {
  sandbox?: SandboxOptions;
}
export interface DurableIsolatesRunner {
  readonly prefixId: string;
  execute: (_: ExecuteOptions) => ExecuteHandle;
  dispose: () => Promise<void>;
}
export interface DurableModule {
  readonly [name: string]: DurableGlobal | DurableModule;
}
export interface ExecuteHandle {
  result: Promise<ExecuteResult>;
  suspend: () => Promise<ExecuteResult>;
}
export interface ExecuteOptions {
  code: string;
  cache: BoundaryCache;
  imports?: PlainImportOverrides;
  globals?: PlainGlobalOverrides;
  durableGlobals?: DurableGlobals;
  durableImports?: Readonly<Record<string, DurableModule>>;
  limits?: Partial<ResourceLimits>;
}
export interface FailedBoundary extends BoundaryRecordBase {
  status: "failed";
  name?: string;
  args?: unknown[];
  error: unknown;
}
export interface FailedResult extends ExecuteResultBase {
  outcome: "failed";
  error: RunError;
  run: RunFailure;
}
export interface NonJsonCallRejection extends NonJsonRejectionBase {
  source: "args" | "result" | "error";
  name: string;
}
export interface NonJsonCommitRejection extends NonJsonRejectionBase {
  source: "commit";
}
export interface PendingOperation {
  id: string;
  name: string;
  payload: unknown;
}
export interface PrepareOptions {
  imports?: Imports;
  globals?: HostGlobals;
  durableGlobals?: DurableGlobals;
  durableImports?: Readonly<Record<string, DurableModule>>;
  limits?: Partial<ResourceLimits>;
}
export interface ProtocolRejection extends RejectionBase {
  reason: "protocol";
  source: "args" | "commit";
  name?: string;
  detail: string;
}
export interface RejectedResult extends ExecuteResultBase {
  outcome: "rejected";
  rejection: Rejection;
  run: RunResult;
}
export interface RunOptions extends Omit<PrepareOptions, "limits"> {
  code: string;
  cache: BoundaryCache;
  limits?: Partial<OneOffResourceLimits>;
}
export interface SuspendedResult extends ExecuteResultBase {
  outcome: "suspended";
  pending: PendingOperation[];
  run: RunResult;
}
export interface UnknownGlobalRejection extends RejectionBase {
  reason: "unknown-global";
  name: string;
}
export interface WaitingBoundary extends BoundaryRecordBase {
  status: "waiting";
  name: string;
  args: unknown[];
}
// #endregion

// #region Types
export type BoundaryCache = Record<string, BoundaryRecord>;
export type BoundaryRecord = CompletedBoundary | FailedBoundary | WaitingBoundary;
export type CreateDurableIsolates = (_?: DurableIsolatesOptions) => DurableIsolates;
export type DurableGlobal = (..._: any[]) => unknown;
export type DurableGlobals = Readonly<Record<string, DurableGlobal>>;
export type ExecuteResult = CompletedResult | SuspendedResult | FailedResult | RejectedResult;
export type NonJsonRejection = NonJsonCallRejection | NonJsonCommitRejection;
export type PlainGlobalOverrides = Readonly<Record<string, HostExportFunction>>;
export type PlainImportOverrides = Readonly<Record<string, HostModuleObject>>;
export type Rejection = NonJsonRejection | DivergenceRejection | DuplicateKeyRejection | UnknownGlobalRejection | ProtocolRejection;
// #endregion

// #region Classes
export declare class SuspendIsolate extends Error {
  readonly payload: unknown;
  constructor(_?: unknown);
}
// #endregion

// #region Variables
export declare const durableIsolates: CreateDurableIsolates;
export declare const KERNEL_BRIDGE_GLOBALS: readonly [typeof DURABLE_CALL_GLOBAL, typeof DURABLE_LOOKUP_GLOBAL, typeof DURABLE_COMMIT_GLOBAL];
// #endregion

// #region Referenced (internal)
interface BoundaryRecordBase {
  seq: number;
  scope?: string;
  order?: number;
}
interface ExecuteResultBase {
  cache: BoundaryCache;
  run: RunResult;
}
interface NonJsonRejectionBase extends RejectionBase {
  reason: "non-json";
  detail: string;
}
interface RejectionBase {
  key: string;
  message: string;
}
// #endregion