/**
 * Generated by tsnapi — public API snapshot of `durable-isolates/internal`
 */
// #region Interfaces
export interface DurableIsolatesInternal {
  durableCall: DurableCall;
  durableLookup: DurableLookup;
  durableCommit: DurableCommit;
  boundary: Boundary;
  nextKey: NextKey;
}
// #endregion

// #region Types
export type Boundary = <T>(_: string, _: () => T | Promise<T>) => Promise<T>;
export type DurableCall = (_: string, _: string, ..._: unknown[]) => Promise<unknown>;
export type DurableCommit = (_: string, _: unknown) => Promise<void>;
export type DurableLookup = (_: string) => Promise<{
  hit: true;
  value: unknown;
} | {
  hit: false;
}>;
export type NextKey = (_: string) => string;
// #endregion