/**
 * Generated by tsnapi — public API snapshot of `durable-workflows`
 */
// #region Interfaces
export interface ActiveInstanceRecord extends InstanceRecordBase {
  status: "running" | "waiting";
}
export interface CompletedInstanceRecord extends InstanceRecordBase {
  status: "completed";
}
export interface CreateOptions {
  instanceId?: string;
  version?: string;
}
export interface DurableGlobalInput {
  instanceId: string;
  workflow: string;
  run: number;
  stepId: string;
  payload: unknown;
}
export interface DurableWorkflowHost {
  hydrate: (_: WorkflowHydrateOptions) => Promise<WorkflowRunner>;
  dispose: () => Promise<void>;
}
export interface DurableWorkflowsEngine {
  readonly pendingPromises: ReadonlySet<Promise<unknown>>;
  create: (_: string, _?: unknown, _?: CreateOptions) => Promise<RunOutcome>;
  get: (_: string) => Promise<WorkflowInstanceHandle | null>;
  continueWorkflow: (_: string) => Promise<RunOutcome>;
  terminate: (_: string) => Promise<void>;
  evict: (_: string, _: string) => Promise<RunOutcome>;
  restart: (_: string) => Promise<RunOutcome>;
  dispose: () => Promise<void>;
}
export interface DurableWorkflowsOptions {
  sandbox?: SandboxOptions;
  store: WorkflowStore;
  plugins?: Readonly<Record<string, DurableWorkflowsPlugin>>;
  alias?: Readonly<Record<string, string>>;
  limits?: Partial<ResourceLimits>;
  onEvent?: (_: EngineEvent) => void;
}
export interface DurableWorkflowsPlugin {
  id: string;
  shim: string;
  globals: Readonly<Record<string, DurableGlobal>>;
}
export interface FailedInstanceRecord extends InstanceRecordBase {
  status: "failed";
  error: SerializedError;
}
export interface MemoryWorkflowStore extends WorkflowStore {
  deploy: (_: string, _: string, _: string, _?: Partial<ResourceLimits>) => void;
}
export interface PendingOperation {
  stepId: string;
  operation: string;
  payload: unknown;
}
export interface ResolvedDefinition {
  version: string;
  code: string;
  limits?: Partial<ResourceLimits>;
}
export interface SerializedError {
  name: string;
  message: string;
  stack?: string;
  data?: unknown;
  class?: ErrorClass;
}
export interface TerminatedInstanceRecord extends InstanceRecordBase {
  status: "terminated";
}
export interface WorkflowExecuteOptions {
  input?: unknown;
  cache: BoundaryCache;
  globals?: PerExecuteGlobals;
  limits?: Partial<ResourceLimits>;
}
export interface WorkflowHydrateOptions {
  workflow: string;
  plugins?: Readonly<Record<string, ModuleDefinition>>;
  limits?: Partial<ResourceLimits>;
}
export interface WorkflowInstanceHandle {
  readonly id: string;
  status: () => Promise<InstanceStatus>;
  outcome: () => Promise<InstanceOutcome | null>;
}
export interface WorkflowRunner {
  execute: (_: WorkflowExecuteOptions) => ExecuteHandle;
  dispose: () => Promise<void>;
}
export interface WorkflowStore {
  createInstance: (_: InstanceRecord) => Promise<void>;
  getInstance: (_: string) => Promise<InstanceRecord | null>;
  updateInstance: (_: InstanceRecord) => Promise<void>;
  deleteInstance: (_: string) => Promise<void>;
  getCache: (_: string) => Promise<BoundaryCache | null>;
  putCache: (_: string, _: BoundaryCache) => Promise<void>;
  getDefinition: (_: string, _?: string) => Promise<ResolvedDefinition | null>;
}
// #endregion

// #region Types
export type DefineWorkflowsPlugin = <TPlugin extends DurableWorkflowsPlugin>(_: TPlugin) => TPlugin;
export type DurableGlobal = (_: DurableGlobalInput) => unknown;
export type DurableWorkflows = (_: DurableWorkflowsOptions) => DurableWorkflowsEngine;
export type EngineEvent = {
  type: "instance";
  instanceId: string;
  status: InstanceStatus;
  run: number;
} | {
  type: "step";
  instanceId: string;
  stepId: string;
  status: "completed" | "failed" | "waiting";
  run: number;
} | {
  type: "log";
  instanceId: string;
  stepId?: string;
  run: number;
  level: "log" | "warn" | "error";
  args: unknown[];
};
export type ErrorClass = "permanent" | "transient";
export type InstanceOutcome = (InstanceOutcomeBase & {
  status: "completed";
}) | (InstanceOutcomeBase & {
  status: "failed";
  error: SerializedError;
}) | (InstanceOutcomeBase & {
  status: "terminated";
});
export type InstanceRecord = ActiveInstanceRecord | CompletedInstanceRecord | FailedInstanceRecord | TerminatedInstanceRecord;
export type InstanceStatus = InstanceRecord["status"];
export type RunOutcome = (RunOutcomeBase & {
  status: "completed";
}) | (RunOutcomeBase & {
  status: "waiting";
  pending: PendingOperation[];
}) | (RunOutcomeBase & {
  status: "failed";
  error: SerializedError;
});
// #endregion

// #region Functions
export declare function durableWorkflowHost(_?: DurableIsolatesOptions): DurableWorkflowHost;
export declare function durableWorkflows(_: DurableWorkflowsOptions): DurableWorkflowsEngine;
export declare function memoryStore(): MemoryWorkflowStore;
// #endregion

// #region Variables
export declare const INTERNAL_SPECIFIER: string;
export declare const WORKFLOW_SPECIFIER: string;
// #endregion