/**
 * Generated by tsnapi — public API snapshot of `durable-workflows/internal`
 */
// #region Interfaces
export interface DurableWorkflowsInternal {
  operation: Operation;
  boundary: Boundary;
}
// #endregion

// #region Types
export type Boundary = <T>(_: string, _: () => T | Promise<T>) => Promise<T>;
export type Operation = (_: string, ..._: unknown[]) => Promise<unknown>;
// #endregion